insert into searchFilters (searchID, filter) values (20, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (14, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (34, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (20, 'Main Campus');
insert into searchFilters (searchID, filter) values (9, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (8, 'Graduate Level');
insert into searchFilters (searchID, filter) values (8, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (30, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (29, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (7, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (20, 'Main Campus');
insert into searchFilters (searchID, filter) values (3, 'Main Campus');
insert into searchFilters (searchID, filter) values (27, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (7, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (28, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (26, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (6, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (35, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (17, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (32, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (26, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (30, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (35, 'Main Campus');
insert into searchFilters (searchID, filter) values (10, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (28, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (13, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (9, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (9, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (29, 'Main Campus');
insert into searchFilters (searchID, filter) values (4, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (2, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (17, 'Main Campus');
insert into searchFilters (searchID, filter) values (3, 'Main Campus');
insert into searchFilters (searchID, filter) values (3, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (24, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (34, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (12, 'Main Campus');
insert into searchFilters (searchID, filter) values (22, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (9, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (30, 'Main Campus');
insert into searchFilters (searchID, filter) values (11, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (1, 'Main Campus');
insert into searchFilters (searchID, filter) values (11, 'Main Campus');
insert into searchFilters (searchID, filter) values (35, 'Graduate Level');
insert into searchFilters (searchID, filter) values (20, 'Graduate Level');
insert into searchFilters (searchID, filter) values (26, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (28, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (18, 'Main Campus');
insert into searchFilters (searchID, filter) values (12, 'Graduate Level');
insert into searchFilters (searchID, filter) values (12, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (23, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (25, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (24, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (5, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (29, 'Graduate Level');
insert into searchFilters (searchID, filter) values (6, 'Graduate Level');
insert into searchFilters (searchID, filter) values (11, 'Graduate Level');
insert into searchFilters (searchID, filter) values (2, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (25, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (35, 'Graduate Level');
insert into searchFilters (searchID, filter) values (25, 'Main Campus');
insert into searchFilters (searchID, filter) values (29, 'Main Campus');
insert into searchFilters (searchID, filter) values (10, 'Main Campus');
insert into searchFilters (searchID, filter) values (7, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (24, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (22, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (25, 'Main Campus');
insert into searchFilters (searchID, filter) values (3, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (12, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (21, 'Main Campus');
insert into searchFilters (searchID, filter) values (27, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (17, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (26, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (9, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (25, 'Main Campus');
insert into searchFilters (searchID, filter) values (30, 'Main Campus');
insert into searchFilters (searchID, filter) values (18, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (23, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (13, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (17, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (11, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (10, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (6, 'Main Campus');
insert into searchFilters (searchID, filter) values (23, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (34, 'Graduate Level');
insert into searchFilters (searchID, filter) values (25, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (5, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (15, 'Main Campus');
insert into searchFilters (searchID, filter) values (8, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (14, 'Graduate Level');
insert into searchFilters (searchID, filter) values (31, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (14, 'Graduate Level');
insert into searchFilters (searchID, filter) values (21, 'Main Campus');
insert into searchFilters (searchID, filter) values (27, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (19, 'Graduate Level');
insert into searchFilters (searchID, filter) values (31, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (1, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (3, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (26, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (2, 'Graduate Level');
insert into searchFilters (searchID, filter) values (34, 'Graduate Level');
insert into searchFilters (searchID, filter) values (8, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (12, 'Graduate Level');
insert into searchFilters (searchID, filter) values (27, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (1, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (18, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (25, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (4, 'Graduate Level');
insert into searchFilters (searchID, filter) values (23, 'Main Campus');
insert into searchFilters (searchID, filter) values (9, 'Main Campus');
insert into searchFilters (searchID, filter) values (23, 'Graduate Level');
insert into searchFilters (searchID, filter) values (32, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (20, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (18, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (28, 'Main Campus');
insert into searchFilters (searchID, filter) values (34, 'Graduate Level');
insert into searchFilters (searchID, filter) values (14, 'Main Campus');
insert into searchFilters (searchID, filter) values (21, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (9, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (35, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (17, 'Graduate Level');
insert into searchFilters (searchID, filter) values (19, 'Main Campus');
insert into searchFilters (searchID, filter) values (29, 'Main Campus');
insert into searchFilters (searchID, filter) values (8, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (35, 'Minimum GPA 3.0');
insert into searchFilters (searchID, filter) values (28, 'Main Campus');
insert into searchFilters (searchID, filter) values (14, 'Graduate Level');
insert into searchFilters (searchID, filter) values (15, 'Minimum GPA 3.5');
insert into searchFilters (searchID, filter) values (6, 'Undergraduate Level');
insert into searchFilters (searchID, filter) values (23, 'Minimum GPA 3.5');
